# O Spring Boot procura os arquivos na pasta 'views' que está na raiz do webapp
spring.mvc.view.prefix=/views/
spring.mvc.view.suffix=.jsp

# Porta que o Render exige (o Spring Boot ajusta automaticamente, mas é bom garantir)
server.port=${PORT:8080}